# Generated by Django 4.0.6 on 2022-07-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(choices=[('30', '1 FL. OZ. or 30 mL'), ('50', '1.7 FL. OZ or 50 mL'), ('75', '2.5 FL. OZ. or 75 mL'), ('100', '3.4 FL. OZ. or 100 mL'), ('125', '4.2 FL. OZ or 125 mL')], default='30', max_length=3),
        ),
    ]
