# Generated by Django 4.0.6 on 2022-07-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_purchase_price_alter_purchase_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(),
        ),
    ]
