# Generated by Django 4.0.6 on 2022-07-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('note', models.CharField(choices=[('top', 'top note'), ('mid', 'middle note'), ('base', 'base note')], default='top', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='fragrance',
            name='notes',
            field=models.ManyToManyField(to='main_app.note'),
        ),
    ]
