# Generated by Django 4.0.6 on 2022-07-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_note_fragrance_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='category',
        ),
    ]
